apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: splitease
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: splitease/auth-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: splitease-config
                  key: DATABASE_URL
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: splitease-config
                  key: REDIS_URL
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: splitease-secrets
                  key: SECRET_KEY
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: splitease-config
                  key: ENVIRONMENT
            - name: FROM_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: splitease-config
                  key: FROM_EMAIL
            - name: SMTP_HOST
              valueFrom:
                configMapKeyRef:
                  name: splitease-config
                  key: SMTP_HOST
            - name: SMTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: splitease-config
                  key: SMTP_PORT
            - name: SMTP_USER
              valueFrom:
                configMapKeyRef:
                  name: splitease-config
                  key: SMTP_USER
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: splitease-secrets
                  key: SMTP_PASSWORD
            - name: APP_URL
              valueFrom:
                configMapKeyRef:
                  name: splitease-config
                  key: APP_URL
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
