apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-service
  namespace: splitease
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-service
  template:
    metadata:
      labels:
        app: expense-service
    spec:
      containers:
        - name: expense-service
          image: splitease/expense-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8002
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: splitease-config
                  key: DATABASE_URL
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: splitease-secrets
                  key: SECRET_KEY
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: splitease-config
                  key: AUTH_SERVICE_URL
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: splitease-config
                  key: ENVIRONMENT
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: splitease-config
                  key: REDIS_URL
          readinessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
